// export-md.js — render the packet (schema + answers) as Markdown.
// Pure: no DOM, testable in node. The .docx exporter mirrors this walk.

import { PACKET } from "./schema.js";

const esc = (s) => String(s ?? "").replace(/\|/g, "\\|").replace(/\r?\n/g, "<br>");

export function exportMarkdown(state) {
  const out = [];
  const meta = state.meta || {};
  out.push(`# ${PACKET.title}${meta.businessName ? ` — ${meta.businessName}` : ""}`);
  out.push("");
  if (meta.filledBy) out.push(`*Filled out by: ${meta.filledBy}*  `);
  if (meta.updated) out.push(`*Last updated: ${meta.updated.slice(0, 10)}*`);
  out.push("");

  const pending = Object.keys(state.suggested || {}).length;
  if (pending > 0) {
    out.push(`> ⚠️ **${pending} machine-suggested value(s) were never confirmed by a person.** Treat those answers as unverified.`);
    out.push("");
  }

  for (const ws of PACKET.worksheets) {
    out.push(`## Worksheet ${ws.num}: ${ws.title}`);
    out.push("");
    const instances = ws.repeatable ? state.data[ws.id] : [state.data[ws.id]];
    if (ws.repeatable && instances.length === 0) {
      out.push("*(not filled out)*", "");
      continue;
    }
    instances.forEach((inst, idx) => {
      if (ws.repeatable) {
        const label = String(inst[ws.instanceLabelField] || `${ws.instanceNoun} ${idx + 1}`);
        out.push(`### ${capitalize(ws.instanceNoun)}: ${label}`);
        out.push("");
      }
      for (const f of ws.fields) {
        const v = inst[f.key];
        if (f.kind === "table") {
          out.push(`**${f.label}**`, "");
          if (Array.isArray(v) && v.length) {
            out.push(`| ${f.columns.map((c) => esc(c.label)).join(" | ")} |`);
            out.push(`| ${f.columns.map(() => "---").join(" | ")} |`);
            for (const row of v) out.push(`| ${f.columns.map((c) => esc(row[c.key])).join(" | ")} |`);
          } else {
            out.push("*(empty)*");
          }
          out.push("");
        } else {
          out.push(`**${f.label}**`, "");
          const text = String(v ?? "").trim();
          out.push(text ? text : "*(no answer)*");
          out.push("");
        }
      }
    });
  }

  out.push("---", "", "*Generated by docs-to-database.*", "");
  return out.join("\n");
}

function capitalize(s) {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

export function downloadText(filename, text, mime = "text/markdown") {
  const blob = new Blob([text], { type: mime + ";charset=utf-8" });
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = filename;
  a.click();
  setTimeout(() => URL.revokeObjectURL(a.href), 5000);
}
